// Copyright Nathan Guerin

#pragma once

#include "NativeGameplayTags.h"

namespace BlasterGameplayTags
{
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Fire);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Reload);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Drop);
	BLASTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ThrowGrenade);
}
